<?php

$jobsList = array();
$jobsList[] = array("Title" => "CARE CENTER MANAGER",
                    "Description" => "Responsible for directing, supervising, and coordinating staff and activities at one of The Villages Health care centers to provide patient-centered, quality, cost-effective care. Management of clerical and clinical supervisors (Clinical Supervisor has dual report to Lead Physician) ",
                    "Qualifications" => array("Three to five years of management experience including at least two years in a health care organization.",
                        "Bachelors degree preferred."),
                    "EssentialDuties" => array("Manages daily operations at care center and coordinates the work activities and schedules.",
                        "Ensures provisions of safe, high-quality patient care by the staff.",
                        "Evaluates performance and recommends merit increases, promotions, and disciplinary actions.",
                        "Ensures that office space, supplies, equipment, and assistance are provided and maintained appropriately for medical staff and patient care.",
                        "Ensures that all business functions are operative and that all processes are effectively and efficiently in place.",
                        "Reviews processes and makes recommendations for improvement. Creates goals for center operations and ensures that these goals are in line with organization goals.",
                        "Operates within the context of an established budget. Makes recommendations for annual budget and maximizes opportunities to meet and exceed budget guidelines.",
                        "Works with department leads to identify professional staff.",
                        "Troubleshoots problems and develops recommendations for resolution",
                        "Monitors staff performance and facilitates effective teamwork",
                        "Other duties as assigned"),
                    "Skills" => array("Knowledge of organization policies and procedures.",
                        "Knowledge of fiscal management and human resource management techniques.",
                        "Knowledge of office management techniques and practices.",
                        "Excellent organizational and time management skills.",
                        "Outstanding verbal and written communication skills.",
                        "Setting, defining, assigning, monitoring, and evaluating outcomes of tasks and goals.",
                        "Skill in problem solving.",
                        "Skill in developing and implementing recruitment materials.",
                        "Excellent organizational skills.",
                        "Ability to clearly communicate and apply policies and principles to solve everyday problems and deal with a variety of situations.",
                        "Ability to plan, exercise initiative, problem solve, make decisions.",
                        "Ability to read, interpret, and apply clinic policies and procedures.",
                        "Ability to identify problems and recommend solutions.",
                        "Ability to establish priorities and coordinate work activities.",
                        "Ability to manage financial information.",
                        "Ability to project positive and professional image.",
                        "Ability to coordinate and prioritize multiple tasks, projects, and schedules.",
                        "Ability to establish and develop effective working relationships.",
                        "Ability to communicate effectively with all levels of employees; facilitate group processes and change.",
                        "Ability to develop/make effective presentations and serve as a trainer when qualified.",
                        "Ability to prioritize and coordinate multiple projects."),
                    "Active" => 1
);
$jobsList[] = array("Title" => "LICENSED PRACTICAL NURSE (LPN)",
                    "Description" => "In the spirit of \"Making People's Dreams Come True\", the candidate for this position is responsible for \"Creating Raving Fans\" by administering nursing care under the supervision of physicians and clinical supervisor.",
                    "Qualifications" => array("High School Diploma",
                        "Graduated from an approved practical nursing program.",
                        "Must have a valid LPN License.",
                        "Clinical experience preferred but not required.",
                        "IV Therapy certificate preferred but not required.",
                        "Familiarity with health care system and knowledge of medical terminology, physiology and pathophysiology",
                        "Basic understanding of EMR preferred but not required.",
                        "Must be able to use proper body mechanics to assist patients."),
                    "EssentialDuties" => array("Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Obtains, verifies, and records health history of patients.  Gathers pertinent health data while reviewing patient's previous records.  Obtains specimens for laboratory analysis.",
                        "Provide basic patient care as ordered: obtains vital signs, administers medications and treatments as directed.  Assists other healthcare professionals in performing exams, diagnostic procedures and treatments, and minor medical procedures.  Adheres to infection control/safety guidelines and confidentiality policies.",
                        "Documents assessments, interventions, patient/family responses, medication dispensed/prescribed, and test results in medical records.",
                        "Promotes wellness by providing patient education materials, communicating physician advice/instructions.  And communicates with other team members to provide a successful patient centered practice."),
                    "Active" => 1
);

$jobsList[] = array("Title" => "TRIAGE NURSE",
                    "Description" => "A nonexempt position responsible for performing a variety of duties in the medical practice. Involved in both the clinical and administrative areas including assisting physicians with patient care and handling clerical, environmental, and organizational tasks. Provides information to patients so they may fully utilize and benefit from the clinical service.",
                    "Qualifications" => array("High school diploma~ or general equivalency diploma (GED)",
                        "Medical assistant diploma from an accredited vocational institution, or a community college course in medical assisting.",
                        "Appropriate certificate indicating passing grade for medical assistant exam preferred.",
                        "Certified medical assistant certification preferred.",
                        "Documented evidence of externship completed in a medical office or facility.",
                        "Current documentation of a national certification for the registered medical assistant (RMA) through the American Medical Technologists (AMT) or for the certified assistant through the American Association of Medical Assistants (AAMA), is recommended but not required. <li>Must possess a current CPR certification and current health records with the appropriate immunizations to work in the health care field (hepatitis B and tuberculosis)."),
                    "EssentialDuties" => array("Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Fulfills patient care responsibilities as assigned that  include checking schedules and organizing patient flow; accompanying patients to exam/procedure room; assisting patients as needed with walking, undressing and dressing, collecting specimens, preparing for exam, etc.; collecting patient history; performing screenings per provider guidelines; assisting physicians/nurses with various procedures; charting; relaying instructions to patients/families; answering calls, and providing pertinent information.",
                        "Fulfills clerical responsibilities as assigned that may include sending/receiving patient medical records; obtaining lab/x-ray reports, hospital notes, referral information, etc.; completing forms/requisitions as needed; scheduling appointments; verifying insurance coverage and patient demographics; managing and updating electronic medical record to ensure that information is complete.",
                        "Fulfills environmental responsibilities as assigned that may include setting up instruments and equipment according to protocols; cleaning visit/procedure rooms, instruments, and equipment between patient visits to maintain infection control; cleaning sterilizer according to scheduled maintenance program and keeping appropriate records; ordering, sorting, storing supplies; and restocking exam/procedure rooms.",
                        "Fulfil1s organizational responsibilities as assigned including respecting/promoting patient rights; responding appropriately to emergency codes; sharing problems relating to patients and/or staff with immediate supervisor.",
                        "Fulfills clinical medical assisting responsibilities that vary according to state law, which may include medical/surgical asepsis, sterilization, instrument wrapping and autoclaving; checking vital signs or instruments; physical examination preparations; clinical pharmacology; drug administration through various routes including injections; prescription verifications with physician's orders; minor surgery assists including surgical tray set-up pre/post surgical care, applying dressings, and suture removal; biohazard waste disposal and monitoring; therapeutic modalities; instructing patients with home care; laboratory procedures including Occupationa1 Safety and Health Administration (OSHA) guidelines; quality control methods; CLIA-waived testing; capillary punctures and venipunctures; specimen handling such as urine, throat, vaginal, stool, and sputum; electrocardiography emergency triage) and first aid. Medical assistants must adhere to the MA scope of practice in the laboratory.",
                        "Communicates with other team members in clinical and clerical area to provide a successful patient centered practice.",
                        "Other duties as assigned."),
                    "Skills" => array("Knowledge of health care field and medical office protocols/procedures.",
                        "Knowledge of specific assisting tasks related to particular medical practice.",
                        "Knowledge of information that must be conveyed to patients and families.",
                        "Skill in performing medical assistance tasks appropriately.",
                        "Skill in tact and diplomacy in interpersonal interactions.",
                        "Skill in understanding patient education needs by effectively sharing information with patients and families.",
                        "Ability to communicate calmly and clearly with patients.",
                        "Ability to learn and retain information regarding patient care procedures.",
                        "Ability to project a pleasant and professional image.",
                        "Ability to plan. Prioritize and complete delegated tasks.",
                        "Ability to demonstrate compassion and caring in dealing with others.",
                        "Ability to work with computer and effectively use electronic medical records (EMR).",
                        "Ability to work under pressure."),
                    "Active" => 0
);


$jobsList[] = array("Title" => "REGISTERED DIETITIAN",
                    "Description" => "Enhance the organization's mission by delivering medical nutrition therapy and nutrition education for patient education.  Provide educational classes to patients of The Villages Health and conduct community education sessions, as requested.  Act as a resource on nutrition topics to clinical staff.",
                    "Qualifications" => array("Current certification ith the Commission on Dietetic Registration and licensure with the Dietetics and Nutrition Practice Council through the Florida Department of Health required.",
                         "Bachelor's degree in nutrition sciences or related field required, Master's preferred.",
                         "Prior experience with chronic disease nutrition counseling, including Diabetes, preferred.",
                         "Current credentialing with Medicare helpful.",
                         "Must be proficient in Microsoft Office and have ability to quickly learn any specific departmental software that may be required.",
                         "Must be extremely organized and flexible to adjust to multipe task request and changing priorities.",
                         "Proven experience as a self-starter who can work with little direction"),
                    "EssentialDuties" => array("Provide medical nutrition therapy to TVH patients in accordnace with Medicare guidelines",
                         "Collaborate with TVH providers to identify and connect with patients in need of nutrition counseling",
                         "Establish treatment plans and follow-up with patients to measure compliance",
                         "Responsible for documenting patient assessments and progress in electronic medical record and other databases",
                         "Participate in developing linkages between nutrition education and other wellness resources",
                         "Act as a nutrition education resource with TVH clinical staff and at community events",
                         "Maintain patient care schedule",
                         "Provide regular reporting to Manager on nutrition education program effectiveness",
                         "Troubleshoot problems and develop recommendations for resolution within the unit",
                         "Other duties as assigned"),
                    "Skills" => array("Outstanding verbal and written communication skills",
                         "Excellent organizational and time management skills",
                         "Excellent public speaking skills",
                         "High level of emotional intelligence",
                         "Setting, defining, assigning, monitoring, and evaluating outcomes of tasks and goals",
                         "Skill in problem solving",
                         "Ability to read, interpret, and apply organizational and department policies and procedures",
                         "Ability to identify problems and recommend solutions",
                         "Ability to flex communication style based on audience",
                         "Ability to establish priorities and coordinate work activities",
                         "Ability to project positive and professional image",
                         "Ability to coordinate and prioritize multiple tasks, projects, and schedules",
                         "Ability to establish and develop effective working relationships",
                         "Ability to communicate effectively with all levels of employees; faciliatate group processes and change",
                         "Ability to develop/make effective presentations and serve as a trainer when qualified"),
                    "Active" => 0
);

$jobsList[] = array("Title" => "PER DIEM DIABETES EDUCATOR",
                    "Description" => "Enhance the organization’s mission by delivering diabetes education through an ADA Education Recognized Program (ADA ERP) for patient education. Provide educational classes to patients of The Villages Health and conduct community education sessions, as requested. Act as a resource on diabetes management to clinical staff.",
                    "Qualifications" => array("Current certification with the National Certification Board for Diabetes Educators (CDE) required.",
                        "Certification in insulin pumps preferred.",
                        "Must be proficient in Microsoft Office and a have ability to quickly learn any specific departmental software that may be required.  ",
                        "Must be extremely organized and flexible to adjust to multiple task requests and changing priorities.  ",
                        "Proven experience as a self-starter who can work with little direction."),
                    "EssentialDuties" => array("Provide both individual and group diabetes education programs following the curriculum established for the ADA ERP certification",
                         "Conduct initial assessments with TVH patients to provide education, coordinate resources, and determine need for diabetes education programs",
                         "Responsible for documenting patient assessments and progress in electronic medical record and other databases",
                         "Set up education area for class sessions and break down materials when complete",
                         "Act as a diabetes education resource with TVH clinical staff and at community events",
                         "Maintain patient care schedule",
                         "Provide regular reporting to Manager on diabetes education program effectiveness",
                         "Troubleshoot problems and develop recommendations for resolution within the unit",
                         "Other duties as assigned"),
                    "Skills" => array("Recognized experience in adult education.",
                         "Excellent organizational and time management skills.",
                         "Outstanding verbal and written communication skills.",
                         "Excellent public speaking skills.",
                         "High level of emotional intelligence.",
                         "Setting, defining, assigning, monitoring, and evaluating outcomes of tasks and goals.",
                         "Skill in problem solving.",
                         "Ability to read, interpret, and apply clinic policies and procedures.",
                         "Ability to identify problems and recommend solutions.",
                         "Ability to flex communication style based on audience.",
                         "Ability to establish priorities and coordinate work activities.",
                         "Ability to project positive and professional image.",
                         "Ability to coordinate and prioritize multiple tasks, projects, and schedules.",
                         "Ability to establish and develop effective working relationships.",
                         "Ability to communicate effectively with all levels of employees; facilitate group processes and change.",
                         "Ability to develop/make effective presentations and serve as a trainer when qualified."),
                    "Active" => 1
);

$jobsList[] = array("Title" => "NURSE PRACTITIONER",
                    "Description" => "This position is responsible for “Creating Raving Fans” by providing primary care services, including assessing, diagnosing, prescribing, treating, and educating patients. Works closely with physicians and other clinicians in a team approach to patient care.",
                    "Qualifications" => array("MSN required.",
                         "Successful completion of advanced practitioner training and certification as a practitioner (general or specialized) from an approved nurse practitioner program. ",
                         "Minimum three years of professional nursing experience in a clinic setting, plus two years of nurse practitioner experience."),
                    "EssentialDuties" => array("Assesses patient status by obtaining health history through patient/family interviews and chart reviews; assessing presenting illness, risk factors, and family history, psychosocial situation, and cultural factors; and performing appropriate physical examination.",
                         "Orders/performs appropriate laboratory diagnostic and other screening tests. Seeks other information as needed, including consultation with physicians and other clinicians, for evaluation of illness. Integrates data to determine diagnosis and therapeutic plan, including identification of any health risks.",
                         "Develops and implements treatment plan by prescribing/dispensing medications and/or injections in compliance with medical practice guidelines and state laws. Handles minor lacerations. Instructs patient/family regarding medications and treatments. Educates patients regarding health promotion/illness prevention. Recommends appropriate community resources to meet patient/family needs. Communicates appropriate case management information to other professionals and community agencies. Prepares documentation for medical records including updating patient medical chart by posting examination and test results, diagnosis, medications, and treatment in written/computerized manner.",
                         "Participates in peer reviews, chart reviews, staff education, clinical guideline development, and other continuing education and quality assurance activities to demonstrate compliance with standards, regulations, policies, and procedures. Acts as consultant/collaborator to clinical team on area of specialty. Complies with patient confidentiality requirements. Promotes patient advocacy.",
                         "Collaborates with physicians in managing acute and long-term medical needs of patient. Provides monitoring and continuity of care between visits according to treatment plan including triaging patient calls/e-mails.",
                         "Other duties as assigned"),
                    "Skills" => array("Knowledge of advanced practice of nursing including anatomy and physiology, pathophysiology, pharmacology and therapeutics, basic nutrition, behavioral factors, psychosocial/family systems, diagnostic testing, interpretation of results and clinical decision making, alternative treatment modalities. ",
                         "Knowledge of professional nursing theory, practices and regulations related to evaluating and providing patient care, and professional ethics related to the delivery of nursing care.",
                         "Knowledge of medical equipment and instruments used to administer patient care.",
                         "Knowledge of common safety hazards and precautions to establish/maintain a safe work environment.",
                         "Knowledge of health promotion, health risk identification, and patient education principles and techniques.",
                         "Knowledge of community, professional, and educational resources.",
                         "Skill in oral and written communication including interviewing to gather medical histories; providing presentations, consultations, facilitation, and documentation, e.g., writing medical orders, patient education materials, and medical record updates. May require skill in using computerized health information management systems.",
                         "Skill in case management, time management, problem solving, crisis intervention, multitasking, and other organizational matters.",
                         "Skill in modifying methods and techniques of professional nursing to provide appropriate nursing care and in initiating appropriate emergency response and investigatory procedures.",
                         "Ability to analyze complex data and draw conclusions.",
                         "Ability to interpret, adapt, and apply guidelines and procedures.",
                         "Ability to establish/maintain effective working relationships with patients, clinical staff, and the public."),
                    "Active" => 1
);

$jobsList[] = array("Title" => "AUDIOLOGY ASSISTANT",
                    "Description" => "A nonexempt position responsible for coordinating, verifying, distributing, and managing all services provided by the organization.",
                    "Qualifications" => array("Minimum one year clerical/billing experience in a health care organization",
                        "This position requires travel between practices using personal vehicle; mileage reimbursement available"),
                    "EssentialDuties" => array("Use customer service principles and techniques to deal with patients calmly and pleasantly",
                        "Schedule patient appointments",
                        "Call patients to verify appointments",
                        "Assist patients with credit applications",
                        "Assist in basic hearing aid cleaning and repair",
                        "Prepare contracts and demo (loaner) forms for hearing aids",
                        "Process/return hearing aids for repair or credit",
                        "Daily cash/invoice tracking and handling",
                        "Assist Controller in reconciling monthly cash and expenses associated with audiology program",
                        "Maintain inventory and track purchase orders for supplies and equipment  ",
                        "Perform insurance eligibility as necessary",
                        "Complete demographic intake in EMR as necessary",
                        "Document patient encounters and phone calls in EMR",
                        "Coordinate 3rd party visits with vendors regarding hearing aids and inspections",
                        "Greet patients and direct them appropriately",
                        "Other duties as assigned"),
                    "Skills" => array("Knowledge of clinic policies and procedures and overall understanding of medical office flow",
                        "Knowledge of coding and clinic operating policies",
                        "Proficient computer program skills ",
                        "Skilled in using a calculator",
                        "Skilled in tact and diplomacy in interpersonal interactions",
                        "Ability to communicate effectively and work with others ",
                        "Ability to communicate calmly and clearly with patients",
                        "Ability to understand and interpret policies and regulations",
                        "Ability to read and interpret medical charts",
                        "Ability to examine documents for accuracy and completeness",
                        "Ability to operate standard office equipment including computers, fax machines, copiers, printers, telephones, calculators, etc."), 
                    "Active" => 0
);
$jobsList[] = array("Title" => "MULTI-SPECIALTY BILLER - BILLING SPECIALIST-PATIENT ACCOUNTS",
                    "Description" => "This position is responsible for “Creating Raving Fans” by being responsible for the day-to-day patient account functions including patient inquiry, problem resolution, and adjustment entry and collection procedures.",
                    "Qualifications" => array("High School Diploma or General Education Degree (GED)",
                        "Some college coursework preferred",
                        "Two years’ experience and working knowledge in medical billing functions of third party payer systems including Medicare and commercial insurance",
                        "Previous Multi-Specialty experience preferred",
                        "Previous experience in operation of office machinery, ie. Copier, fax, computer and printer",
                        "Proficient with Microsoft Office Suite, including Excel, Word and Outlook",
                        "Demonstrated ability to provide excellent customer service to our patients and care center managers"),
                    "EssentialDuties" => array("Assist patients with resolution of account balance problems or discrepancies",
                        "Reconcile daily cash receipts and prepare Daily Close Report",
                        "Monitor claim payments and reconcile denials",
                        "Enter adjustments and submit check requests for refunds as applicable",
                        "Review patient statements and update accounts accordingly",
                        "Analyze accounts receivable and follow-up with third party payers",
                        "Provide billing guidance and support to the front office staff at the care centers",
                        "Post payments and reconcile balances"),
                    "Skills" => array("Ability to read and comprehend simple instructions, short correspondence and memos",
                        "Ability to write simple correspondence",
                        "Ability to effectively present information in one-on-one and small group situations to customers, clients and other employees of the organization",
                        "Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions and decimals",
                        "Ability to compute rate, ratio, and percent and to draw and interpret bar graphs"),
                    "Active" => 0
);
$jobsList[] = array("Title" => "MULTI-SPECIALTY CODER/BILLING SPECIALIST-PATIENT ACCOUNTS",
                    "Description" => "This position is responsible for “Creating Raving Fans” by being responsible for the day-to-day patient account functions including patient inquiry, problem resolution, claims submission, adjustment entry and collection procedures.",
                    "Qualifications" => array("High School Diploma or General Education Degree (GED)",
                        "Some college coursework preferred",
                        "CPC designation preferred",
                        "Previous experience in Multi-Specialty office preferred",
                        "Two years’ experience and working knowledge in medical billing functions of third party payer systems including Medicare and commercial insurance",
                        "Previous experience in operation of office machinery, ie. Copier, fax, computer and printer",
                        "Proficient with Microsoft Office Suite, including Excel, Word and Outlook",
                        "Demonstrated ability to provide excellent customer service to our patients and care center managers"),
                    "EssentialDuties" => array("Review coding data on all Specialty claims prior to submitting to insurance carriers",
                        "Monitor claim payments and reconcile denials.",
                        "Provide on-going support and guidance to fellow coders and others.  Serve as back-up as needed.",
                        "Provide billing guidance to the front office staff at the care centers"),
                    "Skills" => array("Ability to read and comprehend simple instructions, short correspondence and memos",
                        "Ability to write simple correspondence",
                        "Ability to effectively present information in one-on-one and small group situations to customers, clients and other employees of the organization",
                        "Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions and decimals ",
                        "Ability to compute rate, ratio, and percent and to draw and interpret bar graphs"),
                    "Active" => 1
);

$jobsList[] = array("Title" => "CLINICAL SUPERVISOR/PATIENT CARE MANAGER",
                    "Description" => "An exempt position, responsible for oversight of all clinical operations related to nursing and medical support staff in line with clinical practice standards and patient-centered care.",
                    "Qualifications" => array("Licensed RN with a minimum of 3-5 years of supervisory experience- working in a primary care center or related setting with experience in Quality and Process Improvement."),
                    "EssentialDuties" => array("Responsible for collaboration in hiring, firing, training and on-going mentoring of Clinical Supervisors and clinical team members in Care Center assuring that all staff work by the principles of patient-centeredness and mutual respect with colleagues and co-workers.",
                        "Oversee clinical nursing care, ensuring compliance with established regulations and standards including quality assurance, confidentiality and medical record documentation",
                        "Provide collaborative supervision to nurses and subordinate clinical staff, ensuring appropriate assessment and treatment of patient health.",
                        "Responsible for direct supervision of Care Navigators with oversight and management of the Care Navigation Program.",
                        "Oversight of Risk Management duties within TVH.",
                        "Serves as a key problem-solving resource for staff on patient issues  ",
                        "Studies patient needs/trends and suggests solutions to ongoing patient care problems",
                        "Participates in medical practice planning",
                        "Makes sure the performance and productivity of all nursing staff are evaluated regularly throughout the year and annually advises on appropriate corrective actions and development opportunities",
                        "Maintains high quality of care by nursing staff through continuous evaluation and improvement of procedures, protocols and standards",
                        "Ensures all staff are trained in quality assurance and control requirements and meet these standards",
                        "Collaborates with Care Center Manager and Medical Director on development and implementation of nursing department’s mission, goals, policies, procedures, budget, quality assurance plan and work standards",
                        "Communicates with other team members in clinical and clerical area to provide a successful patient centered practice",
                        "Other duties as assigned "),
                    "Skills" => array("Knowledge of nursing principles, practices and procedures; budgetary, supervisory, human resources and quality improvement principles and techniques; clinical state of the art advancements and trends in health care, particularly in the area of Patient Centered Medical Homes; knowledge of principles of employee development to ensure appropriate training and mentoring of staff.",
                        "Skill in applying and modifying, as appropriate, the principles, methods and techniques of professional nursing;",
                        "Skill in identifying problems, researching and recommending solutions;",
                        "Skill in developing and maintaining high levels of quality care and quality assurance;",
                        "Skill in exercising a high degree of initiative, judgment, discretion and decision-making.",
                        "Ability to manage the overall provision of nursing services and build consensus among staff;",
                        "Ability to work effectively with diverse individuals at all levels of the medical practice;",
                        "Ability to handle many tasks simultaneously and deal effectively with changing priorities;",
                        "Ability to demonstrate full range of motion including finger dexterity and eye-hand coordination.",
                        "Ability to work with computers and software programs."),
                    "Active" => 1
);
$jobsList[] = array("Title" => "PHYSICIAN ASSISTANT",
                    "Description" => "This position is responsible for “Creating Raving Fans” by providing primary care services, including assessing, diagnosing, prescribing, treating, and educating patients. Works closely with physicians and other clinicians in a team approach to patient care.",
                    "Qualifications" => array("MSN required.",
                        "Successful completion of advanced practitioner training and certification as a practitioner (general or specialized) from an approved nurse practitioner program.",
                        "Minimum three years of professional nursing experience in a clinic setting, plus two years of nurse practitioner experience."),
                    "EssentialDuties" => array("Assesses patient status by obtaining health history through patient/family interviews and chart reviews; assessing presenting illness, risk factors, and family history, psychosocial situation, and cultural factors; and performing appropriate physical examination.",
                        "Orders/performs appropriate laboratory diagnostic and other screening tests. Seeks other information as needed, including consultation with physicians and other clinicians, for evaluation of illness. Integrates data to determine diagnosis and therapeutic plan, including identification of any health risks.",
                        "Develops and implements treatment plan by prescribing/dispensing medications and/or injections in compliance with medical practice guidelines and state laws. Handles minor lacerations. Instructs patient/family regarding medications and treatments. Educates patients regarding health promotion/illness prevention. Recommends appropriate community resources to meet patient/family needs. Communicates appropriate case management information to other professionals and community agencies. Prepares documentation for medical records including updating patient medical chart by posting examination and test results, diagnosis, medications, and treatment in written/computerized manner.",
                        "Participates in peer reviews, chart reviews, staff education, clinical guideline development, and other continuing education and quality assurance activities to demonstrate compliance with standards, regulations, policies, and procedures. Acts as consultant/collaborator to clinical team on area of specialty. Complies with patient confidentiality requirements. Promotes patient advocacy.",
                        "Collaborates with physicians in managing acute and long-term medical needs of patient. Provides monitoring and continuity of care between visits according to treatment plan including triaging patient calls/e-mails."),
                    "Skills" => array("Knowledge of advanced practice of nursing including anatomy and physiology, pathophysiology, pharmacology and therapeutics, basic nutrition, behavioral factors, psychosocial/family systems, diagnostic testing, interpretation of results and clinical decision making, alternative treatment modalities. ",
                        "Knowledge of professional nursing theory, practices and regulations related to evaluating and providing patient care, and professional ethics related to the delivery of nursing care.",
                        "Knowledge of medical equipment and instruments used to administer patient care.",
                        "Knowledge of common safety hazards and precautions to establish/maintain a safe work environment.",
                        "Knowledge of health promotion, health risk identification, and patient education principles and techniques.",
                        "Knowledge of community, professional, and educational resources.",
                        "Skill in oral and written communication including interviewing to gather medical histories; providing presentations, consultations, facilitation, and documentation, e.g., writing medical orders, patient education materials, and medical record updates. May require skill in using computerized health information management systems.",
                        "Skill in case management, time management, problem solving, crisis intervention, multitasking, and other organizational matters.",
                        "Skill in modifying methods and techniques of professional nursing to provide appropriate nursing care and in initiating appropriate emergency response and investigatory procedures.",
                        "Ability to analyze complex data and draw conclusions.",
                        "Ability to interpret, adapt, and apply guidelines and procedures.",
                        "Ability to establish/maintain effective working relationships with patients, clinical staff, and the public"),
                    "Active" => 1
);
$jobsList[] = array("Title" => "NURSE PRACTITIONER",
                    "Description" => "This position is responsible for “Creating Raving Fans” by providing primary care services, including assessing, diagnosing, prescribing, treating, and educating patients. Works closely with physicians and other clinicians in a team approach to patient care.",
                    "Qualifications" => array("MSN required.",
                        "Successful completion of advanced practitioner training and certification as a practitioner (general or specialized) from an approved nurse practitioner program.",
                        "Minimum three years of professional nursing experience in a clinic setting, plus two years of nurse practitioner experience."),
                    "EssentialDuties" => array("Assesses patient status by obtaining health history through patient/family interviews and chart reviews; assessing presenting illness, risk factors, and family history, psychosocial situation, and cultural factors; and performing appropriate physical examination.",
                        "Orders/performs appropriate laboratory diagnostic and other screening tests. Seeks other information as needed, including consultation with physicians and other clinicians, for evaluation of illness. Integrates data to determine diagnosis and therapeutic plan, including identification of any health risks.",
                        "Develops and implements treatment plan by prescribing/dispensing medications and/or injections in compliance with medical practice guidelines and state laws. Handles minor lacerations. Instructs patient/family regarding medications and treatments. Educates patients regarding health promotion/illness prevention. Recommends appropriate community resources to meet patient/family needs. Communicates appropriate case management information to other professionals and community agencies. Prepares documentation for medical records including updating patient medical chart by posting examination and test results, diagnosis, medications, and treatment in written/computerized manner.",
                        "Participates in peer reviews, chart reviews, staff education, clinical guideline development, and other continuing education and quality assurance activities to demonstrate compliance with standards, regulations, policies, and procedures. Acts as consultant/collaborator to clinical team on area of specialty. Complies with patient confidentiality requirements. Promotes patient advocacy.",
                        "Collaborates with physicians in managing acute and long-term medical needs of patient. Provides monitoring and continuity of care between visits according to treatment plan including triaging patient calls/e-mails."),
                    "Skills" => array("Knowledge of advanced practice of nursing including anatomy and physiology, pathophysiology, pharmacology and therapeutics, basic nutrition, behavioral factors, psychosocial/family systems, diagnostic testing, interpretation of results and clinical decision making, alternative treatment modalities. ",
                        "Knowledge of professional nursing theory, practices and regulations related to evaluating and providing patient care, and professional ethics related to the delivery of nursing care.",
                        "Knowledge of medical equipment and instruments used to administer patient care.",
                        "Knowledge of common safety hazards and precautions to establish/maintain a safe work environment.",
                        "Knowledge of health promotion, health risk identification, and patient education principles and techniques.",
                        "Knowledge of community, professional, and educational resources.",
                        "Skill in oral and written communication including interviewing to gather medical histories; providing presentations, consultations, facilitation, and documentation, e.g., writing medical orders, patient education materials, and medical record updates. May require skill in using computerized health information management systems.",
                        "Skill in case management, time management, problem solving, crisis intervention, multitasking, and other organizational matters.",
                        "Skill in modifying methods and techniques of professional nursing to provide appropriate nursing care and in initiating appropriate emergency response and investigatory procedures.",
                        "Ability to analyze complex data and draw conclusions.",
                        "Ability to interpret, adapt, and apply guidelines and procedures.",
                        "Ability to establish/maintain effective working relationships with patients, clinical staff, and the public."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "X-RAY TECHNICIAN",
                    "Description" => "A nonexempt position responsible for operating X-ray equipment that assists radiologist and/or physicians with diagnosing and/or treating disease and/or injury",
                    "Qualifications" => array("Basic Machine operator (BMO) and licensed by the state of Florida is a requirement",
                        "X-ray experience in the medical environment preferred but not necessary",
                        "Thirteen credits of continuing education every two years are required"),
                    "EssentialDuties" => array("Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Prepares patients for radiologic procedures.  Protects patients, self, and other staff from radiation hazards.",
                        "Takes X-rays following established procedures for patient care and safety, which involves setting up and operating radiographic equipment used in the medical diagnosis and/or treatment of patients and includes implementing infection control procedures for the work area.",
                        "Select proper ionizing factors for radiological diagnosis.  Adjusts/sets radiographic controls.  Positions patients and takes X-rays of specific parts of the patient's body as requested by physicians.  Processes film.  Sends X-rays to appropriate medical staff.",
                        "Maintains required records including patient records, daily log books, and monthly reports.  Performs quanity and quality control checks to assure X-ray unit meets standards required by laws, rules, and departmental policies.  Complies with safety standards.",
                        "Cleans, maintains, and makes minor adjustments to radiographic equipment, including determining equipment repairs.",
                        "Maintain radiographic supplies, film, and orders as necessary.",
                        "Fulfills patient care responsibilities as assigned that include checking schedules and organizing patient flow; accompanying patients to exam/procedure room; assisting patients as needed with walking, undressing and dressing, collecting specimens, preparing for exam, etc.; collecting patient history; performing screenings per provider guidelines; assisting physicians/nurses with various procedures; charting; relaying instructions to patients/families; answering calls, and providing pertinent information.",
                        "Fulfills clerical responsibilities as assigned that may include sending/receiving patient medical records; obtaining lab/x-ray reports, hospital notes, referral information, etc.; completing forms/requisitions as needed; scheduling appointments; verifying insurance coverage and patient demographics; managing and updating electronic medical record to ensure that information is complete.",
                        "Fulfills environmental responsibilities as assigned that may include setting up instruments and equipment according to protocols; cleaning visit/procedure rooms instruments, and equipment between patient visits to maintain infection control; cleaning sterilizer according to scheduled maintenance program and keeping appropriate records; ordering, sorting, storing supplies; and restocking exam/procedure rooms.",
                        "Fulfills clinical medical assisting responsibilities that vary according to state law, which may include medical/surgical asepsis, sterilization, instrument wrapping and autoclaving; checking vital signs or instruments; physical examination preparations; clinical pharmacology; drug administration through various routes including injections; prescription verifications with physician's orders; minor surgery assists including surgical tray set-up pre/post-surgical care, applying dressings, and suture removal; biohazard waste disposal and monitoring; therapeutic modalities; instructing patients with home care; laboratory procedures including Occupational Safety and Health Administration (OSHA) guidelines; quality control methods; CLIA-waived testing; capillary punctures and venipuncture; specimen handling such as urine, throat, vaginal, stool, and sputum; electrocardoigraphy emergency triage) and first aid.  Medical assistants must adhere to the MA scope of practice in the laboratory.",
                        "Communicates with other team members in clinical and clerical area to provide a successful patient centered practice.",
                        "Other duties as assigned"),
                    "Skills" => array("Knowledge of X-ray procedures and protocols",
                        "Knowledge of anatomy and physiology necessary to perform X-ray testing including body mechanics and patient movement.",
                        "Knowledge of radiology equipment including safety hazards common to radiology.",
                        "Skill in positioning patients properly.",
                        "Skill in identifying equipment problems and correcting or notifying supervisor.",
                        "Skill in following infection control and radiological safety procedures.",
                        "Ability to lift and position patients for the X-ray procedure required.",
                        "Ability to notice detail in drawings and differences in shapes and shadings.",
                        "Ability to apply written instructions and standardized work practices"),
                    "Active" => 0
);
$jobsList[] = array("Title" => "CARE NAVIGATOR",
                    "Description" => "A nonexempt position responsible for nursing care under the supervision of Physicians and Clinical Manager.  Care Navigation is a collaborative process which assesses, plans, implements, coordinates, monitors and evaluates the options and services required to meet an individual's health needs, using communication and available resources to promote quality, cost effective outcomes.",
                    "Qualifications" => array("Current, unrestricted RN license in the state of Florida.",
                        "2+ years experience in a hospital or acute care setting with direct patient care",
                        "Case Management experience"),
                    "EssentialDuties" => array("Identify patients appropriate for Care Navigation through referrals and collaboration with PCP and Clinical Teams.",
                        "Establishes a patient specific plan of care based on collaboration with patient/family, providers and payers that identify appropriate levels of care.",
                        "Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Obtains, verifies, and records health history of patients.  Gathers pertinent health data while reviewing patient's previous records.  Populates information fields in the EMR.",
                        "Documents all assessments, plans of care and Care Navigation activites in a timely manner.",
                        "Ensures effective communication and collaboration with multidisciplinary patient care teams.",
                        "Interacts in a collegial and collaborative fashion with outside clinical staff such as specialists, social workers, and other clinical and nonclinical support staff.",
                        "Emphasizes continuity of care and seamless integration during transitions of care to avoid duplication or gaps in plan of care.",
                        "Monitors patient progress while in the acute care and post-acute care settings.  Assist with facilitation of discharge process/transition of care to the appropriate level of care.",
                        "Continue to monitor patient's progress post discharge in an effort to prevent re-admission to acute care and to maximize outcomes.",
                        "Identify opportunities for health promotion and illness prevention.",
                        "Maintains a comprehensive working knowledge of community resources, payer requirements and network services.",
                        "Acts as patient advocate.",
                        "Provides patient education, monitor of health needs and coordination of community resources.  Services may be provided in a variety of settings including clinic, home visits, hospitals or skilled nursing facilities."),
                    "Skills" => array("Knowledge of medical terminology, anatomy, physiology, and pathophysiology.",
                        "Familiarity with health care systems, electronic medical records, regulations, policies, and functions.",
                        "Understanding of documentation standards.",
                        "Knowledge of equipment, supplies, and material needed for medical treatment.",
                        "Understanding of basic laboratory, procedures including preparation and screening.",
                        "Knowledge of infectious disease management and control and safety standards.",
                        "Strong coaching ability.",
                        "Excellent clinical skills and judgment.",
                        "Excellent written and verbal communication skills, with the ability to build relationships.",
                        "Strong ability to work autonomously and be self-directed.",
                        "Strong critical thinking skills.",
                        "Skill in initiating appropriate emergency procedures.",
                        "Skill in handling a number of tasks simultaneously.",
                        "Skills in diplomacy and tact with all interpersonal interactions.",
                        "Ability to communicate calmly and clearly with patients.",
                        "Ability to use manual dexterity to perform medical treatments.",
                        "Ability to establish and maintain effective working relationships with coworkers and diverse patient populations.",
                        "Ability to perform mathematical calculations for drug dosages.",
                        "Ability to work with computer and effectively use electronic medical records (EMR).",
                        "Ability to work under pressure."),
                    "Active" => 0
);

$jobsList[] = array("Title" => "CARE NAVIGATION COORDINATOR",
                    "Description" => "An administrative nonexempt position responsible to support the Care Navigation Program.  This position will interact with the clinical care navigator team members, patients, Providers and other stakeholders.  The coordinator will assist the Care Navigation Team.",
                    "Qualifications" => array("2 plus years of customer service experience analyzing and solving customer problems OR 1 year experience in an office setting environment using the telephone and computer as the primary instrument to perform job duties.",
                        "High school education or GED",
                        "Knowledge of medical terminology, anatomy, physiology, and pathophysiology preferred.",
                        "Certified Medical Assistant Certification is a plus"),
                    "EssentialDuties" => array("Collaboratively works with the Care Navigators, taking direction from them regarding needs.",
                        "Engages with identified beneficiaries to drive service/program awareness and facilitate enrollment into our clinical services and programs.",
                        "Accurately document beneficiary interaction and appropriately follows all processes and procedures related to beneficiary engagement.",
                        "Active surveillance of remote patient monitoring alerts for triage and escalation.",
                        "Accurately manages multiple technology systems simultaneously.",
                        "Builds rapport and established trusted relationships with beneficiaries and Providers.",
                        "Interacts on a regular basis with the Care Navigation Team and Providers.",
                        "Provides excellent customer service to both Providers and patients.",
                        "Consistently meets established productivity, schedule adherence and quality standards while maintaining good attendance.",
                        "Responds to incoming Provider and patient calls.",
                        "Retrieves relevant beneficiary informatino and notifications of Inpatient, ED or SNG admissions or discharges.",
                        "Ensures effective communication and collaboration with multidisciplinary patient care teams.",
                        "Interacts in a collegial and collaborative fashion with outside clinical staff such as specialists, social workers, and other clinical and nonclinical support staff."),
                    "Skills" => array("Excellent organizational, interpersonal, presentation, written and verbal communication skills.",
                        "Ability to communicate in person, by phone, or via e-mail in a professional and friendly manner.",
                        "Excellent customer service skills and attention to detail.",
                        "Ability to empathize, motivate and encourage people toward healthy change, regardless of culture, religion or economic background.",
                        "Ability to work and interact with professionals as part of an interdisciplinary team",
                        "Self-motivated, flexible individual who can flourish in an office setting with colleagues as well as in a self-structured independent setting",
                        "Ability to flourish in an environment where there may be constant change; Applies knowledge/skills to activities that often vary from day to day.",
                        "Ability to multi-task, this includes ability to understand multiple services and multiple delivery modes within each service.",
                        "Ability to prioritize and organize own work to meet agreed upon deadlines.",
                        "Ability to effectively use multiple technology systems to assist with identification and enrollment of patients and review patient data.",
                        "Strong PC computing experience (Microsoft Office and web based tools)",
                        "Familiarity with computer and Windows PC applications, which includes the ability to learn new and complex computer system applications and apply their use",
                        "Model The Villages Health principles of Integrity and Compliance and adhere to our business principles",
                        "Maintain the confidentiality of sensitive information",
                        "Effective interpersonal, collaboration and communication skills"),
                    "Active" => 0
);
$jobsList[] = array("Title" => "LAB TECHNICIAN",
                    "Description" => "A nonexempt position, responsible for providing technical support for laboratory operations.",
                    "Qualifications" => array("High school diploma.",
                        "Successful completion of medical technologist, medical laboratory technician, or certified laboratory assistant program.",
                        "Minimum two years of laboratory experience, preferably in clinic setting.",
                        "American Medical Technologist certification."),
                    "EssentialDuties" => array("Performs technical laboratory functions including chemistry, hematology, urinalysis, immunology, allergy testing, and other tests. Performs echocardiography (EKG), phlebotomy, pulmonary function testing tasks on occasion.",
                        "Reports test results following clinic protocols, alerting physicians and/or nurses immediately about “red flag” results.",
                        "Ensures quality control in collecting specimens and in ensuring appropriate sampling and record keeping. May instruct laboratory assistant on housekeeping and other tasks.",
                        "Maintains equipment, instruments, and supplies as needed.",
                        "Complies with all quality assurance policies and Occupational Safety and Health Administration (OSHA) regulations related to safety, cleanliness, and infection control.",
                        "Other duties as assigned."),
                    "Skills" => array("Knowledge of medical laboratory principles, standards, applications, and tests.",
                        "Knowledge of use and maintenance of laboratory equipment and instruments.",
                        "Knowledge of safety, infection control, and quality assurance policies and regulations.",
                        "Skill in applying appropriate testing procedures.",
                        "Skill in proper use, preventive maintenance, and repair.",
                        "Skill in appropriate quality control and confidentiality procedures.",
                        "Ability to exercise independent judgment, problem solve, make decisions, and use discretion in reporting/distributing results.",
                        "Ability to establish and maintain cooperative relationships with patients, families, and staff.",
                        "Ability to organize workload effectively and work quickly with high level of accuracy using manual/finger dexterity and eye–hand coordination."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "APPLICATION SPECIALIST",
                    "Description" => "Responsible for the implementation and utilization of information systems required for patient care/operational initiatives for all service lines.  Provides technical support to end users.",
                    "Qualifications" => array("Bachelor’s degree from college or certification from a technical school; or two to four years related experience and/or training; or equivalent combination of education and experience.",
                        "Clinical knowledge/background preferred.",
                        "Knowledge of eClinicalWorks Comprehensive Electronic Health Records Solution preferred.",
                        "Will be driving to various locations.  Must have valid driver’s license with record acceptable to company standards."),
                    "EssentialDuties" => array("Provide guidance and support to existing office personnel during the kick off, set up, validation and implementation phases for the transition to eClinicalWorks Comprehensive Electronic Health Records Solution.",
                        "Work closely with clinicians, supervisors, office support/clerical and management-level employees as needed, developing and maintaining rapport in order to facilitate support and identify potential disparities in entry of data, workflow or reporting as it relates to the clinical information system. ",
                        "Plan, host and teach classes and webinars to train and/or re-educate clinicians, supervisors, office support/clerical and management-level employees in appropriate use and functionality of the clinical information system both in the office and in the field.  ",
                        "Review ongoing statistical data to ensure accuracy and integrity of data, providing feedback to staff and/or management on identified trends that indicate opportunities for additional education, enhancement or further evaluation. ",
                        "Utilize strategic analysis skills in order to optimize use of clinical information system, enhance strategic initiatives, provide relevant data to outside sources, and/or other needs as they may arise. ",
                        "Perform administrative functions within the clinical information system, including but not limited to: Patient account creation, deletion, and alterations such as name change due to marriage or divorce; dictionary maintenance; creation and maintenance of forms and reports; and user maintenance.    ",
                        "Manage system upgrades and/or new releases of clinical information system including system file structure maintenance, testing, debugging and communication.  Perform ongoing education to all staff due to changes in system features caused by upgrades and/or new releases as needed. ",
                        "Liaison with Information Technology Solutions Group (TSG) on helpdesk tickets relating to clinical information systems and/or hardware in The Villages Health office locations.  Provide troubleshooting, problem solving and technical support via phone, web and/or in person for efficient and effective problem resolution for end users.  ",
                        "Work collaboratively with the support staff at TSG and/or other clinical/operations system to resolve issues related to the software functionality.",
                        "Participate in the documentation of clinical and business work flows as it relates to the clinical information system. ",
                        "Maintain and update all clinical information training materials including participant manuals, visuals, power point applications and/or vendors.  ",
                        "Participate in organization initiatives as it relates to the evaluation of new clinical and/or operational applications and/or vendors.  ",
                        "Identify, analyze, and repair product failures, order, install and maintain parts as needed.  ",
                        "Has knowledge of commonly-used concepts, practices, and procedures within a particular field, including, but not limited to:  Active Directory, Desktop and Server Management, printer installation/configuration/management/repair, and Software deployment and configuration.  ",
                        "Create and set guidelines in order to efficiently and effectively perform the functions of the job."),
                    "Skills" => array("Ability to read, analyze, and interpret general business periodicals, professional journals, technical procedures, governmental regulations, and procedure manuals.",
                        "Ability to write routine reports, business correspondence, and procedure manuals.",
                        "Ability to effectively present information and respond to questions from groups of managers, clients, customers, and the general public. ",
                        "Ability to add, subtract, multiply, and divide in all units of measure, using whole numbers, common fractions, and decimals.",
                        "Ability to compute rate, ratio, and percent and to draw and interpret bar graphs.",
                        "Ability to calculate figures and amounts such as discounts, interest, commissions, proportions, percentages, area, circumference, and volume. "),
                    "Active" => 0
);


$jobsList[] = array("Title" => "CLINICAL CARE COORDINATOR",
                    "Description" => "Clinical Care Coordinator will engage with an assigned case load of patients focusing on healthcare needs, monitoring of care plans, appointment scheduling and documentation of electronic care plans using Electronic Health Records/management system. Clinical Care Coordinator will work closely with Coder and Medical Providers, and Clinical Assistants.",
                    "Qualifications" => array("Licensed LPN or Certified MA with a minimum of 3-5 years of hands on clinical experience- working in a primary care center or related setting with experience/background in geriatric care, family medicine and/ or internal medicine."),
                    "EssentialDuties" => array("Prep charts in a detailed, granular fashion based on patient medical history, to maximize HCC coding and RAF scores.",
                        "Collect past medical history, HPI and document in patients chart, ensuring CDSS is satisfied.",
                        "Work with Coder to monitor coding/documentation changes to ensure that most current information is available",
                        "Review medical record information to identify all appropriate coding based on CMS HCC categories.",
                        "Develop and implement process and quality improvement initiatives related to pre-visit preparation.",
                        "Complete appropriate paperwork/documentation/system entry based on patient history",
                        "Provide quality documentation, level of service and diagnosis coding consistent with established guidelines and standards.",
                        "Provide real time support and coordination with Primary Care Providers and Staff for HCC coding, HEDIS measures capture.",
                        "Facilitate medical record requests and follow up to confirm receipt of records.",
                        "Assist with telephone encounter and prescription refills for Provider Teams.",
                        "Coordinate with clinical leadership in the development of provider/staff training plans and for active support in the training process/feedback.",
                        "Troubleshoot problems and develop recommendations for resolution.",
                        "Other duties as assigned"),
                    "Skills" => array("Background/experience working with HCC Codes/documentation.",
                        "Critical thinking skills",
                        "Clinical decision making experience",
                        "Competence and experience with electronic charting, preferably with eClinicalworks.",
                        "Excellent organizational and time management skills.",
                        "Outstanding verbal and written communication skills.",
                        "Self –directed with the ability to work independently.",
                        "Medical terminology",
                        "Ability to multi task",
                        "High level of emotional intelligence.",
                        "Setting, defining, assigning, monitoring, and evaluating outcomes of tasks and goals.",
                        "Skill in problem solving.",
                        "Ability to document in an extremely detailed fashion.",
                        "Ability to triage patients and assign care need level.",
                        "Ability to read, interpret, and apply clinic policies and procedures.",
                        "Ability to identify problems and recommend solutions. ",
                        "Ability to establish priorities and coordinate work activities.",
                        "Ability to project positive and professional image.",
                        "Ability to establish and develop effective working relationships.",
                        "Ability to communicate effectively with all levels of employees; facilitate group processes and change.",
                        "Ability to develop/make effective presentations and serve as a trainer when qualified."),
                    "Active" => 0
);

$jobsList[] = array("Title" => "PATIENT SERVICES REPRESENTATIVE",
                    "Description" => "This position is responsible for “Creating Raving Fans” by facilitating the intake process for new patients to The Villages Care Centers.  Will share information and may be the first Villages Health contact with patients to set the stage for a new kind of health care.",
                    "Qualifications" => array("High school diploma.",
                        "Associate’s degree from a community/junior college preferred.",
                        "Minimum two years of customer relations, preferably in medical practice setting.",
                        "Prefer experience in a physician office, primary care setting is ideal.",
                        "Call Center experience preferred."),
                    "EssentialDuties" => array("Clearly communicates information related to The Villages Health",
                        "Facilitation of on-boarding patients including:<br>- Assist patients with patient registration<br>- Verification of health insurance<br>- Assess patients for fit with Care Centers and individual providers<br>- Provide new patient appointment<br>- Tracking of patient information ",
                        "Clearly communicates information related to the Care Center",
                        "Knowledgeable and able to clearly communicate information regarding Medicare and Medicare Advantage products.",
                        "Provides patients with new patient enrollment materials",
                        "Answers all questions of prospective patients, facilitates the answering of questions when answers are not readily available.",
                        "Review all new patient enrollment materials for completeness",
                        "Other duties as assigned."),
                    "Skills" => array("Knowledge of medical terminology.",
                        "Knowledge of health care field.",
                        "Knowledge of legal and ethical considerations related to patient information",
                        "Knowledge of counseling, conflict resolution, and customer service principles and applications.",
                        "Skill in putting information in preferred medical record system, meeting clinic standards.",
                        "Skill in diffusing tense situations through diplomatic problem-solving.",
                        "Skill in using computer and medical records software.",
                        "Ability to communicate effectively with patients and staff via phone, in person and through email.",
                        "Ability to demonstrate leadership in resolving patient concerns.",
                        "Ability to establish relationships with a wide variety of people."),
                    "Active" => 0
);

$jobsList[] = array("Title" => "LEAD CARE NAVIGATOR",
                    "Description" => "A nonexempt position responsible for nursing care under the supervision of Physicians and Clinical Manager.
                        Care Navigation is a collaborative process, which assesses, plans, implements, coordinates, monitors and evaluates the options and services required to meet an individual’s health needs, using communication and available resources to promote quality, cost-effective outcomes.
                        The Lead will primarily function as care navigation within the hospital setting coordinating transitions of care, discharge planning and re-admission prevention.
                        The Lead is responsible to coach, mentor and advocate for the Care Navigation Staff.  They will be the first line, go-to person for Care Navigation staff questions and/or guidance.
                        ",
                    "Qualifications" => array("Current, unrestricted RN license in the state of Florida.",
                        "4+ years experience in a hospital or acute care setting with direct patient care",
                        "Minimum of 2+ years of Case Management experience; preferably Hospital based"),
                    "EssentialDuties" => array("Identify patients appropriate for Care Navigation in the Inpatient setting.",
                        "Identifies and plans strategies to reduce patient length of stay and resource consumption within the care navigation population.",
                        "Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Obtains, verifies, and records health history of patients. Gathers pertinent health data while reviewing patient's previous records. Populates information fields in the EMR.",
                        "Documents all assessments, plans of care and Care Navigation activities in a timely manner.",
                        "Ensures effective communication and collaboration with multidisciplinary patient care teams.",
                        "Acts as an intermediary in a collaborative fashion with outside clinical staff such as specialists, social workers, and other clinical, nonclinical support staff, Physicians and other healthcare institutions.",
                        "Emphasizes continuity of care and seamless integration during transitions of care to avoid duplication or gaps in plan of care.",
                        "Leads by coaching staff to higher levels of performance.",
                        "Identifies opportunities for continuous improvement within the Care Navigation Program.",
                        "Networks/communicates with peer to facilitate operation standards and improvements.",
                        "Models accountability and expects the same from staff.",
                        "Monitors patient progress while in the acute care and post-acute care settings.  Assist with facilitation of discharge process/transition of care to the appropriate level of care.",
                        "Works collegially and collaboratively with hospital-based Case Management Team.",
                        "Works closely with TVH Hospitalist Team during patient hospital stay and with discharge planning.",
                        "Assists clinic-based Care Navigators, as needed, in monitoring patient’s progress post discharge in an effort to prevent re-admission to acute care and to maximize outcomes.",
                        "Identify opportunities for health promotion and illness prevention.",
                        "Maintains a comprehensive working knowledge of community resources, payer requirements and network services.",
                        "Acts as patient advocate.",
                        "Provides patient education, monitor of health needs and coordination of community resources.  Services may be provided in a variety of setting including clinic, home visits, hospitals or skilled nursing facilities."),
                    "Skills" => array("Knowledge of medical terminology, anatomy, physiology, and pathophysiology.",
                        "Familiarity with health care systems, electronic medical records, regulations, policies, and functions. ",
                        "Understanding of documentation standards.",
                        "Knowledge of equipment, supplies, and material needed for medical treatment. ",
                        "Understanding of basic laboratory, procedures including preparation and screening.",
                        "Knowledge of infectious disease management and control and safety standards.",
                        "Strong coaching ability.",
                        "Excellent clinical skills and judgment.",
                        "Excellent written and verbal communication skills, with the ability to build relationships ",
                        "Excellent organizational skills",
                        "Strong ability to work autonomously and be self-directed",
                        "Strong critical thinking skills.",
                        "Skill in initiating appropriate emergency procedures.",
                        "Skill in handling a number of tasks simultaneously.",
                        "Skills in diplomacy and tact with all interpersonal interactions.",
                        "Ability to communicate calmly and clearly with patients.",
                        "Ability to use manual dexterity to perform medical treatments.",
                        "Ability to establish and maintain effective working relationships with coworkers and diverse patient populations.",
                        "Ability to perform mathematical calculations for drug dosages.",
                        "Ability to work with computer and effectively use electronic medical records (EMR).",
                        "Ability to work under pressure. "),
                    "Active" => 0
);
$jobsList[] = array("Title" => "MEMBER SERVICES REPRESENTATIVE/ADVOCATE ",
                    "Description" => "This position is responsible for “Creating Raving Fans” by facilitating the intake process for new patients to The Villages Care Centers.  Will share information and may be the first Villages Health contact with patients to set the stage for a new kind of health care.",
                    "Qualifications" => array("High school diploma.  Associate’s degree from a community/junior college preferred. ",
                        "Minimum two years of customer relations, preferably in medical practice setting.",
                        "Prefer experience in a physician office, primary care setting is ideal."),
                    "EssentialDuties" => array("Facilitation of on-boarding patients includes:<ul><li>Assist patients with obtaining medical records from former providers</li><li>Assist patients with patient registration</li><li>Assess patients for fit with Care Centers and individual providers</li><li>Provide new patient appointment </li></ul>",
                        "Clearly communicates information related to the Care Center",
                        "Provides patients with new patient orientation materials",
                        "Answers all questions of prospective patients, facilitates the answering of questions when answers are not readily available.",
                        "Review all new patient registration materials for completeness",
                        "Other duties as assigned."),
                    "Skills" => array("Knowledge of medical terminology.",
                        "Knowledge of health care field.",
                        "Knowledge of legal and ethical considerations related to patient information",
                        "Knowledge of counseling, conflict resolution, and customer service principles and applications.",
                        "Skill in putting information in preferred medical record system, meeting clinic standards.",
                        "Skill in diffusing tense situations through diplomatic problem-solving.",
                        "Skill in using computer and medical records software.",
                        "Ability to communicate effectively with patients and staff via phone, in person and through email.",
                        "Ability to demonstrate leadership in resolving patient concerns.",
                        "Ability to establish relationships with a wide variety of people."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "AUTHORIZATIONS SPECIALIST",
                    "Description" => "This position is responsible for “Creating Raving Fans” by coordinating, verifying, distributing, and managing all clinical authorizations and services to provide a smooth process for our patients obtaining “buy and bill” prescription, durable medical equipment, and other prescribed treatments needing authorization.",
                    "Qualifications" => array("High school diploma.",
                        "Associate's degree from a community/junior college preferred or medical assistant certification completion.",
                        "Minimum of two years experience working as a clinical assistant in health care.",
                        "Current documentation of a national certification for the regiwstered medical assistant (RMA) through the American Medical Technologiest (AMT) or for the certified medical assistant (CMA) through the American Association of Medical Assistants (AAMA), is required."),
                    "EssentialDuties" => array("Maintain ongoing tracking and appropriate documentation of authorizations of medications for “buy and bill” services",
                        "Assemble information concerning patient's clinical background and authorizations needs",
                        "Per authorization guidelines, provide appropriate clinical information from clinical teams and providers",
                        "Contact review organizations and insurance companies to ensure prior approval requirements are met.  Present necessary medical information such as history, diagnosis and prognosis.",
                        "Review details and expectations about the authorization  process with patients",
                        "Assist patients in problem solving potential issues related to the health care system, financial or social barriers (e.g., establish patient assistance programs, connect with specialty pharmacies).",
                        "Be the system navigator and point of contact for patients and families, with patients and families having direct access for asking questions and raising concerns.  May assume advocate role on the patient's behalf with the carrier to ensure approval of the necessary supplies/services for the patient in a timely fashion.",
                        "Identify and utilize insurance and community resources.  Establish and maintain relationships with identified service providers.",
                        "Ensure that authorizations are addressed in a timely manner and the clinical teams are notified of delays and when complete.",
                        "Remind patients to scheduled appointments when authorizations are completed and meds are available to be administered in office via mail or phone.",
                        "Ensure that patient's specialty care chart is up to date with information on all clinical authorizations obtained.",
                        "Other duties as defined."),
                    "Skills" => array("Knowledge of health care field and medical office protocols/procedures.",
                        "Knowledge of billing practices and clinic policies and procedures",
                        "Knowledge of coding and clinic operating policies.",
                        "Proficient skills in computer programs",
                        "Effective communiciation skills, both verbal and written",
                        "Strong customer service focus",
                        "Ability to take and follow through with tasks and responsibilities",
                        "Ability to read and interpret medical charts.",
                        "Ability to examine documents for information necessary for referrals",
                        "Ability to communicate effectively and work with others."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "PHLEBOTOMIST",
                    "Description" => "This position is responsible for “Creating Raving Fans” by performing venipuncture on patients in a caring and professional manner.",
                    "Qualifications" => array("High school diploma or equivalent.",
                        "Graduation from an accredited medical vocational institution with phlebotomy course diploma.",
                        "Minimum one year of phlebotomy experience.",
                        "Medical practice experience helpful.",
                        "ASCP required; certification as medical assistant preferred but not required.",
                        "National certification through American Medical Technologists as a registered phlebotomy technician not required but helpful.",
                        "Must have a current CPR certificate"),
                    "EssentialDuties" => array("Uses customer service principles and techniques to deal with patients calmly and pleasantly.",
                        "Prepares equipment to efficiently collect blood products.",
                        "Performs venipuncture, arterial and capillary punctures on patients as directed by physician and following medical practice protocols related to safety, infection control, and confidentiality. Conducts laboratory tests on specimens. Enters data into computer.",
                        "Assists donor before, during, and after donation. Instructs on urine collection procedures.",
                        "Cleans/sterilizes equipment, instruments, and work area following safety, cleanliness, and infection control procedures.",
                        "Inventories supplies and places orders to ensure adequate supplies for procedures."),
                    "Skills" => array("Knowledge of phlebotomy techniques.",
                        "Knowledge of clinic protocols and policies.",
                        "Skill in performing efficient and effective draws.",
                        "Skill in conducting cooperative interactions with patients and staff.",
                        "Skill in tact and diplomacy in interpersonal interactions.",
                        "Ability to communicate calmly and clearly with patients.",
                        "Ability to interpret and respond appropriately to instructions.",
                        "Ability to coordinate eye–hand movements to ensure patient comfort during blood draws."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "REFERRAL COORDINATOR",
                    "Description" => "This position is responsible for “Creating Raving Fans” by coordinating, verifying, distributing, and managing all referral services to provide a smooth process for our patients.",
                    "Qualifications" => array("High school diploma.",
                        "Associate’s degree from a community/junior college preferred or medical assistant certification completion.",
                        "Minimum of one year experience in a health care organization involving referrals."),
                    "EssentialDuties" => array("Maintain ongoing tracking and appropriate documentation on referrals.",
                        "Assemble information concerning patient's clinical background and referral needs.",
                        "Per referral guidelines, provide appropriate clinical information to specialist.",
                        "Contact review organizations and insurance companies to ensure prior approval requirements are met. Present necessary medical information such as history, diagnosis and prognosis. ",
                        "Review details and expectations about the referral with patients.",
                        "Assist patients in problem solving potential issues related to the health care system, financial or social barriers (e.g., request interpreters as appropriate, transportation services or prescription assistance).",
                        "Be the system navigator and point of contact for patients and families, with patients and families having direct access for asking questions and raising concerns. May assume advocate role on the patient's behalf with the carrier to ensure approval of the necessary supplies/services for the patient in a timely fashion.",
                        "Identify and utilize cultural and community resources. Establish and maintain relationships with identified service providers.",
                        "Ensure that referrals are addressed in a timely manner.",
                        "Remind patients of scheduled appointments via mail or phone.",
                        "Ensure that patient's primary care chart is up to date with information on specialist consults, hospitalizations, and ER visits.",
                        "Other duties as defined."),
                    "Skills" => array("Knowledge of billing practices and clinic policies and procedures.",
                        "Knowledge of coding and clinic operating policies.",
                        "Proficient skills in computer programs.",
                        "Effective communication skills, both verbal and written.",
                        "Strong  customer service focus",
                        "Ability to take and follow through with tasks and responsibilities.",
                        "Ability to read and interpret medical charts.",
                        "Ability to examine documents for information necessary for referrals.",
                        "Ability to communicate effectively and work with others."),
                    "Active" => 0
);
$jobsList[] = array("Title" => "CLINICAL TRIAGE NURSE",
                    "Description" => "A non-exempt position responsible for providing clinical triage decision making under the supervision of the Lead Clinical Telephone Triage Nurse.  The nurse should be able to prioritize the urgency of the patient telephone interaction based on the assessment data, utilize decision support tools and collaborate with other health care professionals to arrive at a plan of care, implement appropriate interventions, and evaluate the outcome.",
                    "Qualifications" => array("Must have a valid Florida Registered Nurse's License",
                        "BLS Healthcare provider",
                        "Graduate of an accredited school of nursing",
                        "Knowledge of scope of practice for RNs in the State of Florida",
                        "Professional knowledge of clinical nursing protocols in various specialties with emphasis in the areas of disease processes, emergencies, and pharmacology",
                        "Knowledge of what medical symptomology constitutes urgent/emergent care.  Knowledge of medical terminology and abbreviations.",
                        "Knowledge and understanding of managed care concepts strongly recommended.",
                        "Knowledge of clinical protocols for vital signs.  Knowledge of normal values for vital signs (BP, Pulse, Respirations, Temps)",
                        "Knowledge of scheduling practices/referrals for physician offices preferred",
                        "Knowledge of effective teamwork practices between front and back office staff"),
                    "EssentialDuties" => array("Performs nursing assessment of patients with acute and/or chronic health problems via telephone",
                        "Chooses the most appropriate protocol based on the assessment",
                        "Advises the patient and/or the family of the patient on the recommended level of care",
                        "Activates local Emergency Medical Services, as appropriate",
                        "Educates the patient and/or the family regarding recommended care and disease processes",
                        "Follows up on patients via telephone for symptom resolution or disposition",
                        "Reports assessment, findings, and other pertinent information to the Primary Care Physician (PCP) or to the appropriate care management team",
                        "Accurately communicates and documents assessments including recommended interventions within identified time frames",
                        "Schedules and confirms appointments/tests",
                        "Conducts research of available information or community resources",
                        "Assists with training and evaluation of Clinical Telephone Assistants and Clinical Triage Assistants as assigned"),
                    "Skills" => array("Strong critical thinking skills",
                        "Excellent clinical skills and judgment",
                        "Strong coaching ability",
                        "Skill in initiating appropriate emergency procedures",
                        "Skill in handling a number of tasks simultaneously",
                        "Skill for tact and diplomacy in interpersonal interactions",
                        "Ability to communicate calmly and clearly with patients",
                        "Ability to use manual dexterity to perform medical treatments",
                        "Ability to establish and maintain effective working relationships with coworkers and diverse patient populations",
                        "Ability to perform mathematical calculations for drug dosages",
                        "Ability to work with computer and effectively use electronic medical records (EMR)",
                        "Ability to work under pressure"),
                    "Active" => 0
);
$jobsList[] = array("Title" => "BILLING SPECIALIST",
                    "Description" => "Large physician practice in central Florida is looking for an experienced billing supervisor to oversee the day to day operations of the centralized billing office.   This position reports to the Controller.",
                    "Qualifications" => array("Bachelor’s Degree in Business Administration",
                        "Coding Certification",
                        "5-10 years experience managing a billing office function in a large physician practice.",
                        "3-5 years experience with an EMR system",
                        "Complete understanding of major health plans including Medicare, UHC and BCBS."),
                    "EssentialDuties" => array("Develop and implement policies and procedures of the central billing office",
                        "Provide training and support to the practice managers and their staff related to insurance and billing questions.",
                        "Provide high level customer service to patients and operations staff.",
                        "Analyze and report on accounts receivable.",
                        "Provide tools to help billing specialists be able to effectively manage and collect on A/R and work denials."),
                    "Skills" => array("Able to effectively establish and organize workload while being capable of dealing with change well.",
                        "Able to work in a high volume, fast paced environment.",
                        "Able to coach, mentor and train a team of billing specialists.",
                        "Analytical skills to be able to resolve variances and understand data in reports",
                        "Proficient in Microsoft excel",
                        "Customer Service Focused"),
                    "Active" => 1
);

/*
$jobsList[] = array("Title" => "",
                    "Description" => "",
                    "Qualifications" => array(""),
                    "EssentialDuties" => array(""),
                    "Skills" => array(""),
                    "Active" => 0
);
*/

foreach ($jobsList as $key => $value) {
            $JobTitle[$key] = $value["Title"];
      }

      array_multisort($JobTitle, SORT_ASC, $jobsList);
?>




